# Site settings
title: Insanus
description: Site sobre o grupo alpack
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Insanus
user_description: O grupo é formado por estudantes do segundo périodo do C.E.S.A.R school, com o objetivo de se conectar com o mercado e aplicar na prática as atividades aprendidas em classe.
user_title: Projeto NESS
email: insanusstartup@gmail.com
twitter_username: lorem_ipsum
github_username:  ALPACK
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
